### ISSUE TITLE
Fix MacOS compatibility problem

### ISSUE THREAD

**Issue by good-praxis** [good-praxis/Nami#6]
Currently, the glfwGetRequiredExtensions() function returns a nullptr on MacOS.

This needs to be fixed, Vulkan is currently compatible with MacOS, so this should be possible

**Comment by good-praxis** [comment]
Any updates @NoEpicLoot ?

**Comment by LastExceed** [comment]
idk if you noticed this, but 2 years have passed

**Comment by good-praxis** [comment]
Um, actually it's only 1.5 years and that's about how long @NoEpicLoot needs to do anything

**Comment by newtondividedbysqm** [comment]
Just started working on it- ETA in about 2 years.
So let's keep this open.

**Comment by good-praxis** [comment]
Been a bit more than 2 now, how's it going @NoEpicLoot

**Comment by LastExceed** [comment]
i applaud your dedication to the project. without your watchful eye this project would probably have died years ago

**Comment by newtondividedbysqm** [comment]
As of the latest shift in management, MacOS support will be officially dropped from 12th of Feburary onwards,- thus we won't publish any new updates and focus solely on security fixes until that date.

If anyone feels like to continue  support for MacOS they are free to fork and publish this on their own.
